// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Model
{
    [Index("PersonId", Name = "IX_Contracts_PersonId")]
    public partial class Contracts
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Number { get; set; }
        public DateTime Signed { get; set; }
        public bool IsActive { get; set; }
        public int? PersonId { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("Contracts")]
        [JsonIgnore]
        public virtual Persons Person { get; set; }
    }
}